modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "cobblemon_iv_addon"
version = "0.0.1"
displayName = "Cobblemon IV addon"
description = '''

'''

[[dependencies.cobblemon_iv_addon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_iv_addon]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_iv_addon]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "NONE"
side = "BOTH"
